//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        public string employeeId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string birthday { get; set; }
        public string emergencyName { get; set; }
        public string emergencyAddress { get; set; }
        public string emergencyContact { get; set; }
        public string employeeStatus { get; set; }
        public string sssnum { get; set; }
        public string tinnum { get; set; }
        public string dateEmployed { get; set; }
        public string dateFrom { get; set; }
        public string dateTo { get; set; }
        public string signature { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string image { get; set; }
    }
}
